main:
  MAIN_DIR: "/nodo"
  STORAGE: "/nodo/storage"
  CACHE: "/nodo/storage/__cache__/"
  REGISTRY: "/nodo/storage/__registry__/"
  METADATA_REGISTRY: "/nodo/storage/__metadata__/"
  BLOCKDIR: "/nodo/storage/__block__/"
  DATABASE_FILE: "/nodo/storage/database.sqlite"

docker:
  DOCKER_CLIENT_TIMEOUT: 480
  DOCKER_MAX_CONNECTIONS: 1000
  CONCURRENT_CONTAINER_CREATIONS: 10
  REMOVE_CONTAINERS: true

builder:
  WAIT_FOR_CONTAINER: 60
  BUILD_CONTAINER_MEMORY_SIZE_FACTOR: 3.1
  ARM_SUPPORT: true
  X86_SUPPORT: true
  TRUST_METADATA_ARCHITECTURE: false

packer:
  SAVE_ALL: false
  PACKER_MEMORY_SIZE_FACTOR: 2.0
  ARM_PACKER_SUPPORT: true
  X86_PACKER_SUPPORT: true

network:
  GATEWAY_PORT: auto
  NGROK_TUNNELS_KEY: ""
  DOCKER_NETWORK: "docker0"
  LOCAL_NETWORK: "lo"

logs:
  MEMORY_LOGS: false

costs:
  DEFAULT_INITIAL_GAS_AMOUNT_FACTOR: 1e-6
  USE_DEFAULT_INITIAL_GAS_AMOUNT_FACTOR: false
  DEFAULT_INITIAL_GAS_AMOUNT: 1e9
  TOTAL_REFILLED_DEPOSIT: 1e64
  MIN_DEPOSIT_PEER: 1e32
  FREE_TRIAL_GAS_AMOUNT: 1e66
  INITIAL_PEER_DEPOSIT_FACTOR: 0.5
  DEV_CLIENT_GAS_AMOUNT: 1e256
  INIT_COST_CONFIGURATION_FACTOR: 1
  MAINTENANCE_COST_CONFIGURATION_FACTOR: 1e6
  SOCIALIZATION_FACTOR: 2
  COST_AVERAGE_VARIATION: 1
  FREE_GAS_THRESHOLD: 0
  EXECUTION_COST: 1e2
  EXECUTION_BENEFIT: 1e2
  BUILD_COST: 1e1
  MODIFY_RESOURCES_COST: 1e2
  ALLOW_GAS_DEBT: false

timing:
  GENERAL_WAIT_TIME: 2
  GENERAL_ATTEMPTS: 10
  MANAGER_ITERATION_TIME: 10
  SHORT_INTERVAL_COUNT: 100
  COMMUNICATION_ATTEMPTS: 1
  COMMUNICATION_ATTEMPTS_DELAY: 60
  CLIENT_EXPIRATION_TIME: 1200
  EXTERNAL_COST_TIMEOUT: 10
  START_SERVICE_ON_PEER_TIMEOUT: 120

communication:
  SEND_INSTANCE: true
  SEND_ONLY_HASHES_ASKING_COST: true
  DENEGATE_COST_REQUEST_IF_DONT_VE_THE_HASH: false

client:
  MIN_SLOTS_OPEN_PER_PEER: 1
  CLIENT_MIN_GAS_AMOUNT_TO_RESET_EXPIRATION_TIME: 1e3

misc:
  MIN_BUFFER_BLOCK_SIZE: 1e7
  MEMSWAP_FACTOR: 0
  USE_PRINT: false
  VALIDATE_ON_IMPORT: true
  CONFIGURATION_REQUIRED: false

general_flags:
  SIMULATE_PAYMENTS: false
  SUBMIT_REPUTATION_AT_INIT: false
  SUBMIT_NETWORK_ADDRESS_TO_REPUTATION_PROOF: true

reputation:
  LEDGER_REPUTATION_SUBMISSION_THRESHOLD: 10
  TOTAL_REPUTATION_TOKEN_AMOUNT: 1000000000
  REPUTATION_PROOF_ID: ""

payments:
  PAYMENT_MANAGER_ITERATION_TIME: 86400
  PAYMENTS_RECEIVER_WALLET: ""
  DONATION_WALLET: "9gGZp7HRAFxgGWSwvS4hCbxM2RpkYr6pHvwpU4GPrpvxY7Y2nQo"
  DONATION_PERCENTAGE: "0.00"

ledgers:
  - name: ergo
    tags: [ ergo ]
    prose: null
    formal: null

    GAS_PER_ERG: 1e58
    NODE_URL: "https://node.sigmaspace.io"  # ergo_http_peers.json should be there here.
    GENESIS_BLOCK_ID: "b0244dfc267baca974a4caee06120321562784303a8a688976ae56170e4d175b"
    ERG_HOT_WALLET_LIMITS: 100
    WALLET_MNEMONIC: auto
    AUXILIARY_MNEMONIC: auto
    HTTP_PEERS_PATH: "/nodo/storage/ergo_http_peers.json" # delete this.

    PAYMENT_SYSTEM_CONTRACT: ergo # This is the source code route folder, but should be able to specify a service too instead of an internal path.
    REPUTATION_SYSTEM_CONTRACT: ergo
