# -*- coding: utf-8 -*-
# Not generated by bash/generate_protos.sh — hand-written.
#
# bee-rpc-over-grpc-py vendors its own compiled buffer.proto (bee_rpc.buffer_pb2).
# protos/celaut_pb2.py (generated from protos/celaut.proto, which does
# `import "buffer.proto";`) resolves that import as a plain top-level
# `import buffer_pb2`, landing on this module. If this file also called
# AddSerializedFile() for a file named "buffer.proto", protobuf's global
# descriptor pool would reject the second registration with
# "duplicate file name buffer.proto" the moment both this module and
# bee_rpc.buffer_pb2 got imported into the same process.
#
# So there is only one compiled buffer_pb2 at runtime: bee_rpc's. This module
# just aliases to it. protos/buffer.proto stays on disk as the canonical
# schema source for celaut.proto's import and for the Rust TUI build
# (src/commands/tui/build.rs, which has no way to reach into the bee_rpc pip
# package) — keep it byte-for-byte in sync with bee_rpc's own buffer.proto
# when bumping the bee-rpc-over-grpc-py pin in bash/requirements.txt.
import sys as _sys

from bee_rpc import buffer_pb2 as _buffer_pb2

_sys.modules[__name__] = _buffer_pb2
