//  -----------------------
//  -----------------------
//       CEL•AUT•WEB
//  -----------------------
//  -----------------------
syntax = "proto3";
package celaut;


/*
    The formats that have bytes type, such as "formal," will continue to be that way; 
    nodes that have a specific format will be able to add it to their celaut.proto files without any issue... 
    It makes no sense for the message to self-define in those parts, as it goes against the philosophy behind protobuf.
*/

//  -----------------------
//  DEFINITIONS.
//  -----------------------

message DataFormat {
    repeated string tags = 1;
    string prose = 2;
    bytes formal = 3;
}

// TODO Ledger should follow the tags-prose-formal scheme instead of being a simple string.
message ContractLedger {
    bytes contract = 1;
    string contract_addr = 2;
    string ledger = 3;
}

message GasAmount {
    string n = 1;
}

message GasPrice {
    celaut.ContractLedger contract_ledger = 1;
    GasAmount gas_amount = 2;
}

message Metadata {
    message HashTag {
        message Hash {
            bytes type = 1;
            bytes value = 2;
        }
        message AttrHashTag {
            int32 key = 1;  // the attribute's index.
            repeated HashTag value = 2;  // HashTag, if it's a repeated field, the HashTags of every one.
        }
        repeated Hash hash = 1;
        repeated string tag = 2;
        repeated AttrHashTag attr_hashtag = 3; // List of metadata fields. Ordened by indexes defined on format.
    }
    optional HashTag hashtag = 1;
    optional DataFormat format = 2;
    repeated ContractLedger reputation_proofs = 3;
}


//  -----------------------
//  SERVICE SPECIFICATION.
//  -----------------------
message Service {
    // API: Defines how you can interact with the service, the ports where it listens, the communication protocols that it supports, methods and the different errors and responses that it can give.
    message Api {
        message Protocol {
            repeated string tags = 1;
            string prose = 2;
            bytes formal = 3;
        }
        message Slot {
            int32 port = 1;
            repeated Protocol protocol_stack = 2;
        }
        repeated Slot slot = 2;
        repeated GasPrice payment_contracts = 3;
        /*
The cost of the service must be expressed in terms of "gas," an abstract unit that generally represents the costs associated with the service. This unit, called "gas," enables standardized cost measurement, regardless of the payment method used. The service is designed to accept payments through multiple methods, each with a specific parity to "gas," facilitating the conversion of payments made in different forms into an equivalent amount of this unit.

The service may involve two types of costs:

1. **Initial fixed cost**: A one-time payment, expressed in a specific amount of "gas," required to access the service.  
2. **Usage-based cost**: A variable cost, also expressed in "gas," which depends on the level of service utilization by the user.

The detailed specification of these costs—including whether a fixed cost, a usage-based cost, or a combination of both applies, as well as the exact values and specific application conditions—is defined within the API protocol. This definition is tailored to the specific nature of the service and integrated into its technical structure.

### Context within the API
Based on the structure provided in the service message (`message Service`), the elements related to costs and "gas" are primarily linked to the following sections:

- **Api.payment_contracts**: This section details the accepted payment methods and their respective parities with "gas." Each entry in `GasPrice payment_contracts` specifies the conversion rate applicable to a particular payment method, enabling cost calculation in terms of "gas."  
- **Api.slot.protocol_stack.prose**: This includes a textual description explaining how costs in "gas" are calculated, covering both fixed and variable costs, as applicable.  
- **Api.slot.protocol_stack.formal**: If a more rigorous specification is required, this section may contain a formal definition of the costs, possibly using mathematical notation or a technical language, to precisely outline the calculation rules based on usage.

Thus, the API protocol provides users with the necessary information to understand and accurately calculate the costs associated with using the service, ensuring clarity and transparency in their interaction with it.
        */
    }

    // Container:  Specifies the container where the service runs, microarchitecture, entry point and filesystem (DAG?), and environment variables.
    message Container {
        message Architecture {
            repeated string tags = 1;
            string prose = 2;
            bytes formal = 3;
        }
        message Filesystem {
            message ItemBranch {
                message Link {
                    string src = 1;
                    string dst = 2;
                }
                string name = 1; // id for path
                oneof item {
                    bytes file = 2;
                    Link link = 3;
                    Filesystem filesystem = 4;
                }
            }
            repeated ItemBranch branch = 1;
        }
        message Config {
            repeated string path = 1;
            DataFormat format = 2;
        }
        Architecture architecture = 1;
        bytes filesystem = 2;
        map<string, DataFormat> enviroment_variables = 3;
        repeated string entrypoint = 4;
        Config config = 5;
        repeated Api.Protocol node_protocol_stack = 6;  // Expected node protocol stack
    }

    message Network {
        repeated string tags = 1;
        string prose = 2;
        bytes formal = 3;
        repeated Api.Protocol client_protocol_stack = 4;
    }

    string prose = 1;
    Container container = 2;
    Api api = 3;
    repeated Network network = 4;
}


//  ------------------------
//  INSTANCE SPECIFICATION.
//  ------------------------
// Used for specify node peers, node-host instancies, ledger-nodes instancies
message Instance {
    message Uri {
        string ip = 1;
        int32 port = 2;
    }
    message Uri_Slot {
        int32 internal_port = 1;
        repeated Uri uri = 2;
    }
    Service.Api api = 1;
    repeated Uri_Slot uri_slot = 2; // map like [ 8080 -> 192.17.0.4:6899],
}


//  -------------------------------
//  SERVICE INITIAL CONFIGURATION.
//  -------------------------------
// The __config__ file is mounted on each service on the filesystem's root.

message Configuration {
    map<string, bytes> enviroment_variables = 1;
    repeated int32 spec_slot = 2;
}

message ConfigurationFile {
    message NetworkResolution {
        repeated string tags = 1;
        repeated Instance peer_instances = 2;
    }
    Instance gateway = 1;
    Configuration config = 2;
    repeated NetworkResolution network_resolution = 3;
    Sysresources initial_sysresources = 4;
}

//  ------------------------
//  SYSTEM RESOURCES.
//  ------------------------
message Sysresources {                           //  https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.update
    optional uint64 blkio_weight = 1;
    optional uint64 cpu_period = 2;
    optional uint64 cpu_quota = 3;  // https://wbhegedus.me/understanding-kubernetes-cpu-limits/
    optional uint64 mem_limit = 4;
    optional uint64 disk_space = 5;

    // optional double disk_failure_tolerance = 10;
    // optional double process_failure_tolerance = 11;
    // optional double network_failure_tolerance = 12;
}
