# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network_formal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14network_formal.proto\x12\x06\x63\x65laut\"t\n\rNetworkFormal\x12\x33\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\".celaut.NetworkFormal.EntriesEntry\x1a.\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_formal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NETWORKFORMAL_ENTRIESENTRY._options = None
  _NETWORKFORMAL_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_NETWORKFORMAL']._serialized_start=32
  _globals['_NETWORKFORMAL']._serialized_end=148
  _globals['_NETWORKFORMAL_ENTRIESENTRY']._serialized_start=102
  _globals['_NETWORKFORMAL_ENTRIESENTRY']._serialized_end=148
# @@protoc_insertion_point(module_scope)
